ref_genome_fasta: "/n/holylfs05/LABS/informatics/Lab/toga_snakemake_test/AnnotationTOGA/data/headercleaned_GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.fna"
ref_gff3: "/n/holylfs05/LABS/informatics/Lab/toga_snakemake_test/AnnotationTOGA/data/filtered_GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.gff"
genome_fasta: "/n/holylfs05/LABS/informatics/Lab/toga_snakemake_test/AnnotationTOGA/data/headercleaned_GCF_016746365.2_Prin_Dyak_Tai18E2_2.1_genomic.fna"
cactus_hal: "/n/holylfs05/LABS/informatics/Lab/toga_snakemake_test/AnnotationTOGA/data/DmelDpseudoDyak.hal"
cactus_sif: "/n/holylfs05/LABS/informatics/Lab/toga_snakemake_test/AnnotationTOGA/cactus_v2.9.2.sif"
cds_isoforms: "/n/holylfs05/LABS/informatics/Lab/toga_snakemake_test/AnnotationTOGA/data/dmel_CDS_isoforms.tsv"
ref_name: "dmel"
genome_name: "dyak"
toga_path: "/n/holylfs05/LABS/informatics/Lab/toga_snakemake_test/AnnotationTOGA/TOGA/"
toga_config_dir: "/n/home14/afreedman/software/TOGA/my_nextflow_config_files/"
